quick_quote_post_location_threshold:
  type: integer
  default: 3
  description:
    en: "Number of posts back before fast quote enabled."
quick_quote_remove_links:
  type: bool
  default: true
  description:
    en: "Remove all links (inc. pictures) from quotes"
quick_quote_remove_prior_quotes:
  type: bool
  default: true
  description:
    en: "Remove all prior (nested) quotes"
quick_quote_remove_contiguous_new_lines:
  type: bool
  default: true
  description:
    en: "Remove unnecessary new lines"
quick_quote_character_limit:
  type: integer
  default: 400
  description:
    en: "Quote character limit (uses last x chars if total length is greater)"
